### ISSUE TITLE
Grant write access to the ARINENG github organization

### ISSUE THREAD

**Issue by smbambling** [sensu-plugins/sensu-plugins-tomcat#5]
There are several of us here in Operations that can/will assist in maintaining this module.  Can you please grant write access to the ARINENG organization

**Comment by majormoses** [comment]
I am more comfortable granting individual users than an org access unless you disagree, @mattyjones @eheydrick

**Comment by majormoses** [comment]
I checked and as far as I know its not even possible to add an external org, github permissions are really team and user oriented when in the context of an external collaborators.

**Comment by smbambling** [comment]
Ok, can you just add these two guys champain and dmizelle

**Comment by majormoses** [comment]
sure

![image](https://cloud.githubusercontent.com/assets/3145127/26010809/424ca738-3703-11e7-99fd-116fdab94370.png)

Let's in general still follow using pull requests (with a reviewer) and avoid committing directly to master.

**Comment by majormoses** [comment]
I assume I can close this out, feel free to re-open if there is anything that has not been addressed.

**Comment by smbambling** [comment]
Looks good thanks !
