### ISSUE TITLE
Remove badge for code climate

### ISSUE THREAD

**Issue by smbambling** [sensu-plugins/sensu-plugins-tomcat#6]
The badges for code climate are currently broken, can you please create the entires for this project.

https://codeclimate.com/github/sensu-plugins/sensu-plugins-tomcat

**Comment by majormoses** [comment]
I don't think we are using code climate anymore @eheydrick can you confirm? If so I can remove it from the repo here and update the skel.

**Comment by eheydrick** [comment]
I think the token expired. I've never found much value from Codeclimate so I'm fine with killing it.

**Comment by majormoses** [comment]
closed per: https://github.com/sensu-plugins/sensu-plugins-tomcat/commit/29953dfbc15bf3a9a172c2551cf4527ef6cd8388
